# -*- coding: utf-8 -*-
"""Welcome To Colaboratory

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

str="Twinkle, twinkle, little star,\n How I wonder what you are! \n Up above the world so high, \n Like a diamond in the sky.Twinkle, twinkle, little star, \n How I wonder what you are!"
print(str)

import sys
print(sys.version)

r=2.5
pi=3.14
area=pi*r*r
print(area)

a=input("Enter the first name")
b=input("Enter the last name")

firstname = input("Input your First Name : ")
lastname = input("Input your Last Name : ")
print ("" + lastname + " " + firstname)

# This function adds two numbers 

def add(x, y):

   return x + y

 

# This function subtracts two numbers 

def subtract(x, y):

   return x - y

 

# This function multiplies two numbers

def multiply(x, y):

   return x * y

 

# This function divides two numbers

def divide(x, y):

   return x / y

 

def Modulus(x, y):

   return x % y

 

print("Select operation.")

print("1.Add")

print("2.Subtract")

print("3.Multiply")

print("4.Divide")

print("5.Modulus")

 

 

# Take input from the user 

choice = input("Enter choice(1/2/3/4/5):")

 

num1 = int(input("Enter first number: "))

num2 = int(input("Enter second number: "))

 

if choice == '1':

   print(num1,"+",num2,"=", add(num1,num2))

 

elif choice == '2':

   print(num1,"-",num2,"=", subtract(num1,num2))

 

elif choice == '3':

   print(num1,"*",num2,"=", multiply(num1,num2))

 

elif choice == '4':

   print(num1,"/",num2,"=", divide(num1,num2))

 

elif choice == '5':

   print(num1,"%",num2,"=", Modulus(num1,num2))

else:

   print("Invalid input")