# -*- coding: utf-8 -*-
"""Welcome To Colaboratory

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

#for Loop...............
for i in range(1,3,1):
  print(i)

a=["aam","kela","naspatti","mausambi"]
for i in a:
  print(i)

def kela(str):
  str =("hello how are you baby!!!")
  print(str)
  return
kela(str)

print("Opertion with its pin are given here --")
print(" 1:add \n 2:substract \n 3:multiply \n 4:divide")
num=input("Enter the pin according to you :")
x=int(input("Enter the first no for operation :"))
y=int(input("Enter the Second no for operation :"))
def add(x,y):
  if(num=="1"):
    c=x+y
    print("After Addition Result is :",c)
  return
add(x,y)
def substract(x,y):
  if(num=="2"):
    c=x-y
    print("After Substraction Result is :",c)
  return
substract(x,y)
def multiply(x,y):
  if(num=="3"):
    c=x*y
    print("After Multiply Result is :",c)
  return
multiply(x,y)
def divide(x,y):
  if(num=="4"):
    c=x/y
    print("After Divide Result is :",c)
  return
divide(x,y)

