# -*- coding: utf-8 -*-
"""Welcome To Colaboratory

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

#list
list=["abhi","orange","mango"]
#list.insert(2,"suraj")
#print(list.index("orange"))
#print(list.count("mango"))
#list.sort()
#del list[2]
#print(list)

#tuples
tuple=("hello","tata","bugatti")
#t=tuple*30
#print(t)
#print(tuple[0:4])
#print(tuple)

#set data types....
a={1,2,3,4,5,5}
b={6,7,8,2,1,4,5,9}
#print(a,b)
#print(a | b)  #union operation
#print(a & b) # intersaction operation
#print(a-b)   #diffrence operation when the elements of a and b  are deleted the remaining element of a are result.
#print(a^b)    #Symetric operation it deleted the common element in both set and output is the remaining element.

#dictonaries....
pizza={'name':['cheese','paneer','chiken'],'code':['1234','3214','6745'],'shop':['dominos','pizzahut','lazies']}
#print(pizza)
#print(pizza.keys())
#print(pizza.values())
#len(pizza)
#del pizza['name']
#print(pizza)

#Strings.....
str="hello all tomorrow is holiday"
#print(str)
#print(len(str))
#print(str.index('y'))
#print(str.count('o'))
#print(str.upper())
#print(str.lower())
print(str.replace('','.'))