# -*- coding: utf-8 -*-
"""Welcome To Colaboratory

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

#a=4
try:
  if (a>2):
    print("A is bigger than 2..")
except:
  print("A is not defined in the code")