# -*- coding: utf-8 -*-
"""Welcome To Colaboratory

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

#Inheritence........
class pratapgarh:
  def __init__(self):
    print("this is a Pratapgarh")
  def parentfunc():
    print("This is a district pratapgarh..")

#p=pratapgarh()
class nariya(pratapgarh):
  def __init__(self):
    print("this is a nariya ")

  def nariyaFunc():
    print("this is a Village In Pratapgarh ..") 

nariya()
pratapgarh()
nariya.parentfunc()
nariya.nariyaFunc()
