# -*- coding: utf-8 -*-
"""Welcome To Colaboratory

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

#slicing in strings....
s="orange"
#print(s[1:4])
#print(s[1:])
#print(s[:5])
#print(s[1:-4])
#print(s*2)
#print(s[0:5:2]) #range between 0 to 5 but diffrence is 2 so we  have to left one and run simuntaneosly.
#print(len(s))